var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                        xx            xxx   xx                                    ",
   "                                     xxyxx                    xxy                                                  ",
   "            ssssss                              yy                 xxx                                             ",
   "                           yy                        xx    xx    xx!!!   xxyxx                                      ",
   "                      p                      xx                  x!!!!vv                                          ",
   "   yyyyy     xxx                                       ssss           !                                            ",
   "                 xxx       x       xxyxx        vvv     yyxx       v!v                                            ",
   "                     xxx                                                 xxxxx                                    ",
   "  xx      p                        xx                  o                     x                                    ",
   "  x               xyx   o    xxx                      xxxyy            oo    x                                    ",
   "  x ++   xxxxxxx                         xxxxx                      xxxxx    x                                    ",
   "  x       !!!!xxx   xx  o      x  xxxx   x!!!!  yyyxxx   xxx                  x                                    ",
   "  x  @       ==!x         yxx            x!!!!!!!!!!!!!!!!!!!!!! xyyyx   =   x                                    ",
   "  yyyxxxvvv!!!!!xxxxyyyyyx!!!!!!!!yyyyyyyxxxxxxxxxxxxx!!!!!xxxxxxx   xxxxxxxxx                                    ",
   "              !!!         xxxxx!!!x                  x!!!!!x                                                      ",
   "           vv!!!!!!           x!!!x                  x!!!!!x                                                      ",
   "             vvvvv            x!!!x                  x!!!!!x                                                      ",
   "                              xxxxx                  xxxxxxx                                                      ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                      x!!x                        xxvvxxx                                    x!x  ",
   "                                      x!!x  ppp                xxxx                                          x!x  ",
   "                                      x!!xxxxxxxxxx           xx     p                                       x!x  ",
   "                                      xx!!!!!!!!!!xx         xx                                              x!x  ",
   "                                       vxxvxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "               ooo                 ++            xvx         x     x   x                      ===!!!!!!!!!!!!!xx  ",
   "             xxxxxxx                                         xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                  xxxx                        xx!!!!!!!!!!!xx            v                        ",
   "        xxx                                                    xxxx!!!!!xxxx                                      ",
   "                vvv                            x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                  ++           x     x                             x         x                    ",
   "                                               x     x       pp                    xx        x                    ",
   "      xxx        +                             xx    x                             x         x                    ",
   "                                  p            x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxxxxx  x         x        x   x          x     x               x   xxxxx   xxxxxx      x                     ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                       +                                                                      ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x  v     v            xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x     o          xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx              xxxxxx         x  ",
   "  x      p                 x           x            +   p    oo          x   x                             x  ",
   "  x                           xx          x                              x x x      +               oo     x  ",
   "  x                 +                     x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x  p                           x         xxx           p         x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x               +             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          ==        x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                                                                                                x x x         ",
   "                                                                                             o o oxxx x       ",
   "                                                                                                   x          ",
   "                   vvv   vvv  xxxxx  o   o     v     o   xxxxxxx  oo         o                                ",
   "                   vvv   vvv  x   x  o   o     v     o      x     o  o       o                                ",
   "                   vvv   vvv  x   x  o   o     v     o      x     o   o      o                                ",
   "                   vvv   vvv  x   x  o   o     v  x  o      x     o    o     o                                ",
   "                   vvvvvvvvv  x   x  o   o     v  x  o      x     o     o    o                                ",
   "                      vvv     x   x  o   o     v  x  o      x     o      o   o                                ",
   "                      vvv     x   x  o   o     v  x  o      x     o       o  o                                ",
   "                      vvv     x   x  o   o     v  x  o      x     o        o o                                ",
   "                      vvv     xxxxx  ooooo     vvvvvvv   xxxxxxx  o         o                                 ",
   "                                                                                                              ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
